# Generated by Django 3.1.5 on 2021-01-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
